# Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  title: crb API
  version: '0.2'
  description: Copy Service Broker provides a way to
               copy(store) data-stream associated with a copyId
               and retrieve data-stream for a given copyId

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: localhost:8080
basePath: /crb
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: crb-web

################################################################################
#                                  Security                                    #
################################################################################

#todo

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  copyId:
    name: copyId
    in: path
    description: The id of the copy instance.
    type: string
    required: true

  copyData:
    name: copyData
    in: body
    description: copy data as octet stream
    required: true
    schema:
      $ref: '#/definitions/InputStream'

  copyMeta:
    name: copyMeta
    in: body
    description: copy metadata
    required: true
    schema:
      $ref: '#/definitions/CopyMetaData'

  repoId:
    name: repoId
    in: path
    description: The id of the copy repository instance
    type: string
    required: true

  repoIdInQuery:
    name: repoIdInQuery
    in: query
    description: The id of the copy repository instance
    type: string
    required: false

  pageNumber:
    name: pageNumber
    in: query
    description: 'page number of paginated list. e.g. copies list'
    type: integer
    format: int32
    required: false

  pageSize:
    name: pageSize
    in: query
    description: 'page size of paginated list. e.g. copies list'
    type: integer
    format: int32
    required: false

  repoInfo:
    name: repoInfo
    in: body
    description: repository access info
    required: true
    schema:
      $ref: '#/definitions/RepositoryInfo'

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /info:
    get:
      tags:
        - crb-web
      summary: Gets CRB info
      description: Return crb info
      operationId: getInfo
      parameters: []
      responses:
        200:
          description: Successfully returned crb info
          schema:
            $ref: '#/definitions/Info'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'

  /repositories/{repoId}:
    post:
      tags:
          - crb-web
      summary: Store repository info of specified repoId.
      description: Store repository configuration info.
      operationId: storeRepositoryInfo
      parameters:
        - $ref: '#/parameters/repoId'
        - $ref: '#/parameters/repoInfo'
      responses:
        201:
          description: Successfully created a repo info in Metadata-DB
          schema:
            $ref: '#/definitions/RepositoryInstance'
        409:
          description: A repository instance with the same repoId exists. Either
                       use different repoId or delete existing repoId instance
                       before retrying
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error - Most likely Metadata-DB not accessible
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
    get:
      tags:
          - crb-web
      summary: Get repository config info of repoId instance
      description: Return configuration info of a specific repository instance
      parameters:
        - $ref: '#/parameters/repoId'
      operationId: getRepositoryInfo
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/RepositoryInfo'
        400:
          description: Bad Request - malformed request
          schema:
            $ref: '#/definitions/error'
        404:
          description: Repository instance of specified repoId does not exist
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error -- most likely Metadata-DB not accessible
          schema:
            $ref: '#/definitions/error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'
    put:
      tags:
          - crb-web
      summary: Update (or create if not present) repository info of specified repoId.
      description: Update (or create if not present) repository config info.
      operationId: updateRepositoryInfo
      parameters:
        - $ref: '#/parameters/repoId'
        - $ref: '#/parameters/repoInfo'
      responses:
        200:
          description: Successfully updated a repo info in Metadata-DB
          schema:
            $ref: '#/definitions/RepositoryInstance'
        500:
          description: Internal error - Most likely Metadata-DB not accessible
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
        - crb-web
      summary: Delete a repository instance.
      description: Delete a repository instance of specified repoId.
                   Copy data in that repository is not deleted;
                   however copy data will not be accessible after
                   deleting repository instance
      operationId: deleteRepository
      parameters:
        - $ref: '#/parameters/repoId'
      responses:
        200:
          description: Success - Successful operation
          schema:
            type: string
        404:
          description: Repository instance of specified repoId does not exist
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error -- Most likely Metadata-DB could not be
                       accessed
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'

  /repositories/{repoId}/stats:
    get:
      tags:
          - crb-web
      summary: Get stats of the repoId such as used/available space etc.
      description: Return metadata associated with the repository with repoId
      parameters:
        - $ref: '#/parameters/repoId'
      operationId: getRepositoryStats
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/RepositoryStats'
        204:
          description: No repoId in Metadata-DB
        500:
          description: Internal error -- most likely Metadata-DB not accessible
          schema:
            $ref: '#/definitions/error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'

  /repositories/{repoId}/copies/{copyId}/data:
    post:
      tags:
        - crb-web-data
      summary: Create copy -- store copy data
      description: Store copy instance data in the specified repo
                   and create a Metadata-DB entry for this copy
      operationId: createCopyInRepo
      consumes:
        - application/octet-stream
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/repoId'
        - $ref: '#/parameters/copyId'
        - $ref: '#/parameters/copyData'
      responses:
        201:
          description: Successfully created a copy of the data and an entry in
                       the Metadata-DB
          schema:
            type: string
            description: Copy URL - http://<crb-endpoint>/copies/<copyId>
        404:
          description: Repository repoId instance is not configured
          schema:
            $ref: '#/definitions/error'
        409:
          description: A copy instance with the same copyId exists. Either use
                       different copyId or delete existing copyId instance
                       before retrying
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error. Data could not be copied to copy-repo or
                       copy instance metadata could not be created. If copy
                       instance metadata can't be created, copy instance will be
                       deleted
          schema:
            $ref: '#/definitions/error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'

  /repositories:
    get:
      tags:
          - crb-web
      summary: Get a list of configured repositories managed by this CRB
      description: Return a list of provisioned repositories
      operationId: listRepositoryInstances
      parameters: []
      responses:
        200:
          description: Successfully listed Repo instances managed by crb
          schema:
            type: array
            items:
              $ref: '#/definitions/RepositoryInstance'
            description: repoId is currently used to access RepositoryInstance.
        204:
          description: No repositories content in Metadata-DB
        500:
          description: Internal error -- most likely Metadata-DB not accessible
          schema:
            $ref: '#/definitions/error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'

  /copies/{copyId}/data:
    get:
      tags:
        - crb-web-data
      summary: Retrieve copy data
      description: Copy instance data is fetched from copy-repo and streamed back
      operationId: retrieveCopy
      consumes:
        - application/json
      produces:
        - application/octet-stream
      parameters:
        - $ref: '#/parameters/copyId'
      responses:
        200:
          description: Successfully retrieved copy instance data and streamed
                       back
          schema:
            $ref: '#/definitions/OutputStream'
        404:
          description: Copy instance with specified copyId does not exist.
                       If copy instance loss is permanent, client should
                       delete this copy instance.
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error -- most likely access issue with copy-repo
                       or with Metadata-DB
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'

  /copies:
    get:
      tags:
      - crb-web
      summary: List all the current copy instances.
      description: Return copyIds from Metadata-DB
      operationId: getCopyInstances
      parameters:
        - $ref: '#/parameters/repoIdInQuery'
        - $ref: '#/parameters/pageNumber'
        - $ref: '#/parameters/pageSize'
      responses:
        200:
          description: Successfully listed copy instances managed by crb
          schema:
            type: array
            items:
              $ref: '#/definitions/CopyInstance'
            description: copyId is currently used to access CopyInstance.
        204:
          description: Operation succeeded; however, currently no copies are
                       managed by crb
        500:
          description: Internal error -- Most likely Metadata-DB could not be
                       accessed
          schema:
            $ref: '#/definitions/error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'

  /copies/{copyId}:
    post:
      tags:
        - crb-web
      summary: Store a copy instance meta data
      description: Store a copy instance attributes
      operationId: storeCopyMetaData
      parameters:
        - $ref: '#/parameters/copyId'
        - $ref: '#/parameters/copyMeta'
      responses:
        201:
          description: Successfully stored copy instance attributes
          schema:
            $ref: '#/definitions/CopyInstance'
        409:
          description: A copy instance with the same copyId exists. Either use
                       different copyId or delete existing copyId instance
                       before retrying
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error -- Most likely Metadata-DB could not be
                       accessed
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
    get:
      tags:
        - crb-web
      summary: Get copy instance meta data
      description: Return copy instance attributes
      operationId: getCopyMetaData
      parameters:
        - $ref: '#/parameters/copyId'
      responses:
        200:
          description: Successfully returned copy instance attributes
          schema:
            $ref: '#/definitions/CopyMetaData'
        404:
          description: Copy instance of specified copyId does not exist
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error -- Most likely Metadata-DB could not be
                       accessed
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
        - crb-web
      summary: Delete a copy data instance as well as its metadata
      description: Delete copy instance of specified copyId along with its
                   metadata
      operationId: deleteCopy
      parameters:
        - $ref: '#/parameters/copyId'
      responses:
        200:
          description: Success - Successful operation
          schema:
            type: string
        404:
          description: Copy instance of specified copyId does not exist
          schema:
            $ref: '#/definitions/error'
        500:
          description: Internal error -- Most likely Metadata-DB could not be
                       accessed
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'

################################################################################
#                               Definitions                                    #
################################################################################
definitions:
  Info:
    type: object
    properties:
      name:
        type: string
        description: crb service name
      version:
        type: string
        description: crb microservice version
      build:
        type: string
        description: crb microservice software build number
      repoType:
        type: string
        description: crb managed repositories type
    example:
      name: crb
      version: '0.1'
      build: '0.1.0.116'
      repoType: file

  error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
    example:
      code: 'other than 500 that implementation may support -  e.g. 599'
      message: 'message for the error code - e.g., filesystem connection timeout'

  supportedProtocol:
    type: object
    required:
    - protocol
    - version
    - endpoint
    - credentials
    properties:
      protocol:
        type: string
      version:
        type: string
      endpoint:
        type: object
        properties:
          addr:
            type: string
            description: basic IP addr of dns name
          endPointAdditionalInfo:
            type: object
            additionalProperties:
              type: string
              description: Can include arbitrary string to string mappings of
                          key-value pairs to describe endpoint
      credentials:
        type: object
        properties:
          user:
            type: string
          password:
            type: string
          credentialsAdditionalInfo:
            type: object
            additionalProperties:
              type: string
              description: Can include arbitrary string to string mappings of
                          key-value pairs (such as account key info) that could
                          be required to gain access to the endpoint.
      copyLocation:
        type: object
        properties:
          path:
            type: string
            description: Optional input of copies' location.  Could be absolute
                         path on a mounted filesystem. Appropriate default
                         should be used (such as /var/lib/crb).
          copyLocationAdditionalInfo:
            type: object
            additionalProperties:
              type: string
              description: Can include arbitrary string to string mappings of
                          key-value pairs to specify a location within a container.
  RepositoryInfo:
    type: object
    properties:
      id:
        type: string
        description: Globally unique key for a configured copy repository.
                     This id is provided to crb and later used to specify
                     which repository copy should be saved.
      name:
        type: string
        description: (optional) User friendly name configured for copy repository
      repoSupportedProtocols:
        type: array
        items:
          $ref: '#/definitions/supportedProtocol'
      repoAdditionalInfo:
        type: object
        additionalProperties:
          type: string
          description: Can include arbitrary string to string mappings of
                       key-value pairs about the copy repo

    example:
      id: 247b0da2-2b88-11e7-93ae-92361f002671
      name: test-dev-file-server
      repoSupportedProtocols: '[{ protocol:nfs, version:4.1,
                                  endpoint:{addr: 192.168.10.10, endpointAdditionalInfo{location:Hopkinton}},
                                  credentials:{user:xyz, password:abc, credentialsAdditionalInfo:{key:MY_KEY, secret:MY_SECRET}},
                                  copyLocation:{path:/var/lib/crb/, copyLocationAdditionalInfo:{mountpoint:/var}},
                                  repoAdditionalInfo: {}
                                 }]'
      repoAdditionalInfo: '{fileServer:Dell Precision Tower}'

  RepositoryStats:
    type: object
    properties:
      totalCapacityInBytes:
        type: integer
        description: total capacity in bytes
        format: int64
      usedCapacityInBytes:
        type: integer
        description: total capacity already used in bytes
        format: int64
      availableCapacityInBytes:
        type: integer
        description: total capacity available in bytes
        format: int64
      numberOfCopiesStored:
        type: integer
        format: int32
    example:
      totalCapacityInBytes: 1073741824000
      usedCapacityInBytes: 73741824000
      availableCapacityInBytes: 33632358400
      numberOfCopiesStored: 1036

  RepositoryInstance:
    type: object
    description: RepoURLs
    properties:
      repoId:
        type: string
      repoURL:
        type: string
    example:
      repoURL: 'http://<crb-endpoint>/repositories/<repoId>'
      repoId: 'arbitrary-repo-id'

  CopyInstance:
    type: object
    description: copyURL
    properties:
      copyURL:
        type: string
    example:
      copyURL: 'http://<crb-endpoint>/copies/<copyId>'

  InputStream:
    type: object
    format: binary
    description: Octet Stream

  OutputStream:
    type: object
    format: binary
    description: Octet Stream

  CopyMetaData:
    type: object
    properties:
      copyId:
        type: string
        description: Unique copy Id
      repoId:
        type: string
        description: Unique Copy Repository Id
      copyTimeStamp:
        type: string
        description: Time when copy is initiated & completed in UTC
        format: date-time
      protocol:
        type: string
        description: Protocol used to make this copy
      protocolVersion:
        type: string
        description: version of protocol used to make this copy
      facility:
        type: string
        description: facility used by copy initiator in order to take the copy
      copyDataURL:
        type: string
        description: Link to the location of the copy data
      copyAdditionalInfo:
        type: object
        additionalProperties:
          type: string
          description: Can include arbitrary string to string mappings of
                       key-value pairs about the copy instance such as
                       copySourceSizeInBytes, platform org & space, DSB used
                       for copy, application using this data, etc. CRB server
                       can also fill additional properties such as
                       copyTargetSizeInByte, copySizeReductionPercentage etc.
                       CRB client will persist this information for a later
                       retrieval by CRB client.
    example:
      copyId: f4d1912a-2b87-11e7-93ae-92361f002671
      copyTimeStamp: '2017-03-09T13:06:08.260Z'
      protocol: nfs
      protocolVersion: '4.1'
      copyDataURL: 'http://<crb-endpoint>/copies/<copyId>/data'
      copyAdditionalInfo: '{copySourceSizeInBytes: 1018518509,
                            org:cndp, space:saruman, dsb:mysql-dsb, app:hackathon,
                            copyTargeSizeInBytes: 123456789,
                            copySizeReductionPercentage: 825}'